export const ACTIONS = {
  SET_USERS: "SET_USERS",
  SET_POSTS: "SET_POSTS",
  SET_POSTS_ON_FEED: "SET_POSTS_ON_FEED",
  LIKE_POST: "LIKE_POST",
  DISLIKE_POST: "DISLIKE_POST",
  ADD_TO_BOOKMARK: "ADD_TO_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  SET_BOOKMARKS: "SET_BOOKMARKS",
  CREATE_NEW_POST: "CREATE_NEW_POST",
  DELETE_POST: "DELETE_POST",
  EDIT_POST: "EDIT_POST",
};
